### ISSUE TITLE
can i disable it for some lines?

### ISSUE THREAD

**Issue by arcifius** [sjova/vscode-sass-format#16]
I'm trying to do:
```css
// sass-lint:disable-all
:root {
    --background-image: url("nonrelevanturl");
}
// sass-lint:enable-all
```
But linter still warning and stopping the formatting
Error is: Invalid CSS after "...kground-image: ": expected "}", was "url("..."
