### ISSUE TITLE
format `background` property shorthand semantically

### ISSUE THREAD

**Issue by iFwu** [sjova/vscode-sass-format#7]
Something like: 

```css
span {
      background: no-repeat left center / 17px auto url('./img/icon-gps.png');
}
```
will be converted to:
```
span {
      background: no-repeat left (center / 17px) auto url('./img/icon-gps.png');
}
```

In such shorthand, `/` in `left center / 17px auto` is meant to separate `background-position` and `background-size` in order to aviod ambiguity.

I hope this plugin can recognize it and do not wrap it in parentheses.
